[package]
edition = "2021"
name = "holomessage"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
hdk = { workspace = true }
holomessage_integrity = { workspace = true }

[dev-dependencies]
holochain = { workspace = true }
tokio = { workspace = true }
