[package]
edition = "2021"
name = "profiles"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# hc_zome_profiles_coordinator = {git = "https://github.com/holochain-open-dev/profiles", branch = "build/holochain-0.3.x"}
hc_zome_profiles_coordinator = "0.2"
