[package]
edition = "2021"
name = "holomess_integrity"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { workspace = true }
hdi = { workspace = true }
serde = { workspace = true }
